name: 'PR Lint'
description: 'Lint PR Titles'
inputs:
    commitlint:
        description: 'Is commitlint enabled'
        required: true
    jirakey:
        description: 'Jira Key'
        required: true
runs:
    using: 'node12'
    main: 'index.js'