name: 'PR Lint'
description: 'Lint PR Titles'
author: 'henrygriffiths'
branding:
    icon: chevron-right
    color: blue
inputs:
    issuekey:
        description: 'Issue Key'
        required: true
    prtitle:
        description: 'PR Title'
        required: false
    types:
        description: 'Lint Types'
        required: false
runs:
    using: 'node16'
    main: './dist/index.js'
