name: 'PR Lint'
description: 'Lint PR Titles'
author: 'henrygriffiths'
branding:
    icon: chevron-right
    color: blue
inputs:
    issuekey:
        description: 'Issue Key'
        required: true
    prtitle:
        description: 'PR Title'
        required: false
    types:
        description: 'Lint Types'
        required: false
    allownokey:
        description: 'Allow No Issue Key'
        required: false
        default: true
    nokeyword:
        description: 'No Issue Key Word'
        required: false
        default: 'none'
runs:
    using: 'node16'
    main: './dist/index.js'
