name: 'PR Lint'
on:
    pull_request:
        types:
            - opened
            - synchronize
            - edited

jobs:
    pr_lint:
        runs-on: ubuntu-latest
        name: pr_lint
        steps:
          - name: pr_lint
            id: lint
            uses: HenryGriffiths/pr_lint@${{ github.head_ref }}
            with:
                jirakey: 'JIRA'
