name: 'PR Lint'
on:
    pull_request:
        types:
            - opened
            - synchronize
            - edited

jobs:
    pr_lint:
        runs-on: ubuntu-latest
        name: pr_lint
        steps:
          - name: checkout
            uses: actions/checkout@v2
          - name: pr_lint
            id: lint
            uses: ./
            with:
                jirakey: 'JIRA'
