name: 'PR Lint'
on:
  pull_request:
    types:
    - opened
    - synchronize
    - edited

jobs:
  pr_lint_pass:
    runs-on: ubuntu-latest
    name: pr_lint_pass
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_pass
      id: pr_lint_pass
      uses: ./
      with:
        issuekey: 'issue'
        prtitle: 'test: issue-123: example title'

  pr_lint_pass_nokey:
    runs-on: ubuntu-latest
    name: pr_lint_pass_nokey
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_pass_nokey
      id: pr_lint_pass_nokey
      uses: ./
      with:
        issuekey: 'issue'
        prtitle: 'test: none: example title'

  pr_lint_pass_multikey:
    runs-on: ubuntu-latest
    name: pr_lint_pass_multikey
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_pass_multikey
      id: pr_lint_pass_multikey
      uses: ./
      with:
        issuekey: 'issue,bug'
        prtitle: 'test: bug-123, issue-123: example title'

  pr_lint_pass_multimultikey:
    runs-on: ubuntu-latest
    name: pr_lint_pass_multimultikey
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_pass_multimultikey
      id: pr_lint_pass_multimultikey
      uses: ./
      with:
        issuekey: 'issue,bug,key'
        prtitle: 'test: bug-123, issue-123, key-123: example title'

  pr_lint_pass_scope:
    runs-on: ubuntu-latest
    name: pr_lint_pass_scope
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_pass_scope
      id: pr_lint_pass_scope
      uses: ./
      with:
        issuekey: 'issue'
        prtitle: 'test(deps): issue-123: example title'

  pr_lint_pass_nonalpha_key:
    runs-on: ubuntu-latest
    name: pr_lint_pass_nonalpha_key
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_pass_nonalpha_key
      id: pr_lint_pass_nonalpha_key
      uses: ./
      with:
        issuekey: 'issue7'
        prtitle: 'test: issue7-123: example title'

  pr_lint_pass_nonalpha_scope:
    runs-on: ubuntu-latest
    name: pr_lint_pass_nonalpha_scope
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_pass_nonalpha_scope
      id: pr_lint_pass_nonalpha_scope
      uses: ./
      with:
        issuekey: 'issue'
        prtitle: 'test(deps-dev): issue-123: example title'

  pr_lint_pass_multiscope:
    runs-on: ubuntu-latest
    name: pr_lint_pass_multiscope
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_pass_multiscope
      id: pr_lint_pass_multiscope
      uses: ./
      with:
        issuekey: 'issue'
        prtitle: 'test(deps, docs): issue-123: example title'

  pr_lint_pass_breakingchange:
    runs-on: ubuntu-latest
    name: pr_lint_pass_breakingchange
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_pass_breakingchange
      id: pr_lint_pass_breakingchange
      uses: ./
      with:
        issuekey: 'issue'
        prtitle: 'test!: issue-123: example title'

  pr_lint_pass_manualtype:
    runs-on: ubuntu-latest
    name: pr_lint_pass_manualtype
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_pass_manualtype
      id: pr_lint_pass_manualtype
      uses: ./
      with:
        issuekey: 'issue'
        prtitle: 'test: issue-123: example title'
        types: 'feat,ci,test'

  pr_lint_fail_type:
    runs-on: ubuntu-latest
    name: pr_lint_fail_type
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_fail_type
      id: pr_lint_fail_type
      continue-on-error: true
      uses: ./
      with:
        issuekey: 'issue'
        prtitle: 'testing: issue-123: example title'
    - name: Invert Status
      run: |
        if [[ ${{ steps.pr_lint_fail_type.outcome }} == "failure" ]]; then exit 0; else exit 1; fi

  pr_lint_fail_multitype:
    runs-on: ubuntu-latest
    name: pr_lint_fail_multitype
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_fail_multitype
      id: pr_lint_fail_multitype
      continue-on-error: true
      uses: ./
      with:
        issuekey: 'issue'
        prtitle: 'feat: test: issue-123: example title'
    - name: Invert Status
      run: |
        if [[ ${{ steps.pr_lint_fail_multitype.outcome }} == "failure" ]]; then exit 0; else exit 1; fi

  pr_lint_fail_key:
    runs-on: ubuntu-latest
    name: pr_lint_fail_key
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_fail_key
      id: pr_lint_fail_key
      continue-on-error: true
      uses: ./
      with:
        issuekey: 'issue'
        prtitle: 'test: issues-123: example title'
    - name: Invert Status
      run: |
        if [[ ${{ steps.pr_lint_fail_key.outcome }} == "failure" ]]; then exit 0; else exit 1; fi

  pr_lint_fail_multikey:
    runs-on: ubuntu-latest
    name: pr_lint_fail_multikey
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_fail_multikey
      id: pr_lint_fail_multikey
      continue-on-error: true
      uses: ./
      with:
        issuekey: 'issue'
        prtitle: 'test: issue-123issue-1234: example title'
    - name: Invert Status
      run: |
        if [[ ${{ steps.pr_lint_fail_multikey.outcome }} == "failure" ]]; then exit 0; else exit 1; fi

  pr_lint_fail_multikey_spacing:
    runs-on: ubuntu-latest
    name: pr_lint_fail_multikey_spacing
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_fail_multikey_spacing
      id: pr_lint_fail_multikey_spacing
      continue-on-error: true
      uses: ./
      with:
        issuekey: 'issue'
        prtitle: 'test: issue-123,issue-1234: example title'
    - name: Invert Status
      run: |
        if [[ ${{ steps.pr_lint_fail_multikey_spacing.outcome }} == "failure" ]]; then exit 0; else exit 1; fi

  pr_lint_fail_nonalpha_scope:
    runs-on: ubuntu-latest
    name: pr_lint_fail_nonalpha_scope
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_fail_nonalpha_scope
      id: pr_lint_fail_nonalpha_scope
      continue-on-error: true
      uses: ./
      with:
        issuekey: 'issue'
        prtitle: 'test(deps!): issue-123: example title'
    - name: Invert Status
      run: |
        if [[ ${{ steps.pr_lint_fail_nonalpha_scope.outcome }} == "failure" ]]; then exit 0; else exit 1; fi

  pr_lint_fail_multiscope:
    runs-on: ubuntu-latest
    name: pr_lint_fail_multiscope
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_fail_multiscope
      id: pr_lint_fail_multiscope
      continue-on-error: true
      uses: ./
      with:
        issuekey: 'issue'
        prtitle: 'test(deps)(docs): issue-123: example title'
    - name: Invert Status
      run: |
        if [[ ${{ steps.pr_lint_fail_multiscope.outcome }} == "failure" ]]; then exit 0; else exit 1; fi

  pr_lint_fail_multiscope_comma:
    runs-on: ubuntu-latest
    name: pr_lint_fail_multiscope_comma
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_fail_multiscope_comma
      id: pr_lint_fail_multiscope_comma
      continue-on-error: true
      uses: ./
      with:
        issuekey: 'issue'
        prtitle: 'test(deps,docs): issue-123: example title'
    - name: Invert Status
      run: |
        if [[ ${{ steps.pr_lint_fail_multiscope_comma.outcome }} == "failure" ]]; then exit 0; else exit 1; fi

  pr_lint_fail_emptyscope:
    runs-on: ubuntu-latest
    name: pr_lint_fail_emptyscope
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_fail_emptyscope
      id: pr_lint_fail_emptyscope
      continue-on-error: true
      uses: ./
      with:
        issuekey: 'issue'
        prtitle: 'test(): issue-123: example title'
    - name: Invert Status
      run: |
        if [[ ${{ steps.pr_lint_fail_emptyscope.outcome }} == "failure" ]]; then exit 0; else exit 1; fi

  pr_lint_fail_space:
    runs-on: ubuntu-latest
    name: pr_lint_fail_space
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_fail_space
      id: pr_lint_fail_space
      continue-on-error: true
      uses: ./
      with:
        issuekey: 'issue'
        prtitle: 'test:issue-123: example title'
    - name: Invert Status
      run: |
        if [[ ${{ steps.pr_lint_fail_space.outcome }} == "failure" ]]; then exit 0; else exit 1; fi

  pr_lint_fail_trailingspace:
    runs-on: ubuntu-latest
    name: pr_lint_fail_trailingspace
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_fail_trailingspace
      id: pr_lint_fail_trailingspace
      continue-on-error: true
      uses: ./
      with:
        issuekey: 'issue'
        prtitle: 'test: issue-123:example title'
    - name: Invert Status
      run: |
        if [[ ${{ steps.pr_lint_fail_trailingspace.outcome }} == "failure" ]]; then exit 0; else exit 1; fi

  pr_lint_fail_manualtype:
    runs-on: ubuntu-latest
    name: pr_lint_fail_manualtype
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_fail_manualtype
      id: pr_lint_fail_manualtype
      continue-on-error: true
      uses: ./
      with:
        issuekey: 'issue'
        prtitle: 'test: issue-123: example title'
        types: 'ci,build,docs'
    - name: Invert Status
      run: |
        if [[ ${{ steps.pr_lint_fail_manualtype.outcome }} == "failure" ]]; then exit 0; else exit 1; fi

  pr_lint_checktitle:
    runs-on: ubuntu-latest
    name: pr_lint_checktitle
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pr_lint_checktitle
      id: pr_lint_checktitle
      continue-on-error: true
      uses: ./
      with:
        issuekey: 'issue'
        prtitle: 'test: issue-123: example title'
