name: 'PR Lint'
on:
    pull_request:
        types:
            - opened
            - synchronize

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            uses: HenryGriffiths/pr_lint@v1
            with:
                jirakey: 'JIRA'
